---
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    ports:
      - "9042:9042"
    volumes:
      - ./schema.cql:/schema.cql
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=DevCluster
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    restart: unless-stopped

volumes:
  cassandra_data:
